mod_version = 1.0.0
maven_group = com.uncannyvoxel
archives_base_name = uncannyvoxel

# Fabric Loom properties
minecraft_version = 1.21.11
yarn_mappings = 1.21.11+build.6:v2
loader_version = 0.19.3
fabric_version = 0.141.5+1.21.11

# JVM args for client testing
run.client.jvmargs = -Dfabric-api.gametest=true -Dfabric.dli.disable=true

# Access widener for GameTest
accesswidener = true
