mod_version = 1.0.0
maven_group = com.uncannyvoxel
archives_base_name = uncannyvoxel

# Fabric Loom properties
minecraft_version = 26.2
yarn_mappings = 26.2+build.1:v2
loader_version = 0.16.0
fabric_version = 0.100.0+26.2

# JVM args for client testing
run.client.jvmargs = -Dfabric-api.gametest=true -Dfabric.dli.disable=true

# Access widener for GameTest
accesswidener = true